load("//stark-bazel:stark.bzl", "stark_module")

stark_module(
    name = "fs",
    srcs = ["src/fs.st"],
    visibility = ["//visibility:public"],
)

stark_module(
    name = "str",
    srcs = ["src/str.st"],
    visibility = ["//visibility:public"],
)