name: Build

on: [push]

env:
  CC: /usr/bin/clang
  CXX: /usr/bin/clang++

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1

    - name: Debug
      run: |
        cc --version
    
    - name: Mount bazel cache
      uses: actions/cache@v1
      with:
        path: "/home/runner/.cache/bazel"
        key: bazel

    - name: Install bazelisk
      run: |
        curl -LO "https://github.com/bazelbuild/bazelisk/releases/download/v1.1.0/bazelisk-linux-amd64"
        mkdir -p "${GITHUB_WORKSPACE}/bin/"
        mv bazelisk-linux-amd64 "${GITHUB_WORKSPACE}/bin/bazel"
        chmod +x "${GITHUB_WORKSPACE}/bin/bazel"

    - name: Test stdmods
      run: |
        "${GITHUB_WORKSPACE}/bin/bazel" test //stdmods:all

    - name: Build examples
      run: |
        "${GITHUB_WORKSPACE}/bin/bazel" build //examples:all