name: Build

on: [push]

env:
  CC: /usr/bin/clang
  CXX: /usr/bin/clang++

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1

    - name: Install tools
      run: |
         if [ "$RUNNER_OS" == "Linux" ]; then
              sudo apt-get update 
              sudo apt-get -y install git cmake bison libfl-dev flex ninja-build
              sudo apt-get purge --auto-remove llvm
              wget https://apt.llvm.org/llvm.sh
              chmod +x llvm.sh
              sudo ./llvm.sh 10
              echo LLVM default version is $(/usr/bin/llvm-config-10 --version)
         else
              brew install llvm
         fi
    
    - name: Mount bazel cache
      uses: actions/cache@v1
      with:
        path: "/home/runner/.cache/bazel"
        key: bazel

    - name: Install bazelisk
      run: |
        curl -LO "https://github.com/bazelbuild/bazelisk/releases/download/v1.1.0/bazelisk-linux-amd64"
        mkdir -p "${GITHUB_WORKSPACE}/bin/"
        mv bazelisk-linux-amd64 "${GITHUB_WORKSPACE}/bin/bazel"
        chmod +x "${GITHUB_WORKSPACE}/bin/bazel"

    - name: Test stdmods
      run: |
        "${GITHUB_WORKSPACE}/bin/bazel" test //stdmods:all

    - name: Build examples
      run: |
        "${GITHUB_WORKSPACE}/bin/bazel" build //examples:all