name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout sources
      uses: actions/checkout@v1

    - name: Install clang
      uses: egor-tensin/setup-clang@v1
      with:
        version: latest
        platform: x64

    - name: Install bazelisk
      run: |
        curl -LO "https://github.com/bazelbuild/bazelisk/releases/download/v1.1.0/bazelisk-linux-amd64"
        mkdir -p "${GITHUB_WORKSPACE}/bin/"
        mv bazelisk-linux-amd64 "${GITHUB_WORKSPACE}/bin/bazel"
        chmod +x "${GITHUB_WORKSPACE}/bin/bazel"
    
    - name: Install native dependencies
      run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
              sudo apt-get update 
              sudo apt-get -y install libcurl4-openssl-dev
          fi
    

    - name: Mount bazel cache
      uses: actions/cache@v1
      with:
        path: "/home/runner/.cache/bazel"
        key: bazel


    - name: Test stdmods
      run: |
        "${GITHUB_WORKSPACE}/bin/bazel" test //stdmods:all

    - name: Build examples
      run: |
        "${GITHUB_WORKSPACE}/bin/bazel" build //examples:all